Naam = input('Naam? | ')
Adres = input('Adres? | ')
Postcode = input('Postcode? | ')
Woonplaats = input('Woonplaats? | ')

print('----------------------------------------------------')
print('|  Naam      : ' + Naam)              
print('|  Adres     : ' + Adres)         
print('|  Postcode  : ' + Postcode)                    
print('|  Woonplaats: ' + Woonplaats)               
print('----------------------------------------------------')
